name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: login dockerhub
      env:
        DOCKER_USER:  ${{ secrets.DOCKER_USER }}
        DOCKER_PASS:  ${{ secrets.DOCKER_PASS }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        echo "fin login"

    - name: build image
      run: |
        docker build -t jormeno2020/los_cantores_pizzeria .

    - name: push image
        run: |
          docker push -t jormeno2020/los_cantores_pizzeria

      
